### PR TITLE
Completion scopes and built-in php functions

### LINKED ISSUE #7: Add completion for php defaults functions and classes

### PR DESCRIPTION
**Pull request by mkusher**
Fixes #7  
Main goal is different visibility scopes like FileScope, MethodScope, IfScope, ForeachScope and other, so that situations like `if ($a instanceof SomeClass)` could be resolved locally for if-block

### CODE REVIEW

**Comment by mkusher** [comment]
deepinscreenshot20150927131214

**Comment by mkusher** [comment]
or even so
deepinscreenshot20150927135336

**Comment by mkusher** [comment]
I think it is almost done, but I want to do some refactoring

**Comment by MichaelMackus** [comment]
:+1: would love to see this merged!

**Comment by mkusher** [comment]
@MichaelMackus hi, sorry for a long PR, will try to finish asap

**Comment by tmsanrinsha** [comment]
I want to use this feature.
Could you update the version of packagist?
[mkusher/padawan - Packagist](https://packagist.org/packages/mkusher/padawan)

I can't resolve pacakge requirement.

```
$ composer global require mkusher/padawan:dev-master
Changed current directory to /Users/tmsanrinsha/.composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: react/http[dev-master, v0.4.1].
    - Can only install one of: react/http[v0.4.1, dev-master].
    - Can only install one of: react/http[dev-master, v0.4.1].
    - don't install react/http dev-master|don't install react/react v0.4.1
    - mkusher/padawan dev-master requires react/http dev-master -> satisfiable by react/http[dev-master].
    - Installation request for mkusher/padawan dev-master -> satisfiable by mkusher/padawan[dev-master].
    - Installation request for react/http == 0.4.1.0 -> satisfiable by react/http[v0.4.1], react/react[v0.4.1].
```

**Comment by mkusher** [comment]
@tmsanrinsha hi!

Master already has this feature and it looks like master is up-to-date https://github.com/mkusher/padawan.php/blob/master/composer.json#L24

**Comment by tmsanrinsha** [comment]
Old padawan package caused this promblem. I removed old padawan and then installed new padawan.

**Pull request merged**
